### ISSUE TITLE
Cache feed.clj and all-jars.clj

### ISSUE THREAD

**Issue by tobias** [librariesio/clojars-json#12]
The data feeds from clojars are only updated hourly, so it is of no benefit to request them for every incoming request. Clojars also now provides a gzipped version of `all-jars.clj`, which is 350KB vs 3.9MB for the uncompressed version.

I'd be happy to provide a PR to cache these (and request the compressed version of all-jars) if you like.

**Comment by andrew** [comment]
@tobias thanks for the info, a PR would be wonderful!

**Comment by andrew** [comment]
Fixed in #14 and shipped!
